// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type Item struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Image     *graphql.Upload `json:"image"`
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
}

type NewItem struct {
	Name   string          `json:"name"`
	Imange *graphql.Upload `json:"imange"`
}
