version: '3.8'
services:
  mongo:
    image: mongo
    container_name: app_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo-data-volume:/data/db
      - mongo-configdb-volume:/data/configdb
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    container_name: app_mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo-data-volume:
    external: false
  mongo-configdb-volume:
    external: false
  yarn-cache:

networks:
  app-network:
    driver: bridge
